package gui;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKor_1 = new javax.swing.JLabel();
        lblNev_1 = new javax.swing.JLabel();
        txtKor = new javax.swing.JTextField();
        txtNev_1 = new javax.swing.JTextField();
        lblKor_2 = new javax.swing.JLabel();
        lblNev_2 = new javax.swing.JLabel();
        txtNev_2 = new javax.swing.JTextField();
        numKor = new javax.swing.JSpinner();
        btnFeldolgoz_1 = new javax.swing.JButton();
        btnFeldolgoz_2 = new javax.swing.JButton();
        lblVisszajelzes = new javax.swing.JLabel();
        btnVeletlenszamok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKor_1.setText("Kor:");

        lblNev_1.setText("Név:");

        lblKor_2.setText("Kor:");

        lblNev_2.setText("Név:");

        numKor.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));

        btnFeldolgoz_1.setText("Feldolgoz");
        btnFeldolgoz_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeldolgoz_1ActionPerformed(evt);
            }
        });

        btnFeldolgoz_2.setText("Feldolgoz");
        btnFeldolgoz_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeldolgoz_2ActionPerformed(evt);
            }
        });

        btnVeletlenszamok.setText("Véletlenszámok");
        btnVeletlenszamok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeletlenszamokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKor_1)
                                            .addComponent(lblNev_1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNev_1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnFeldolgoz_1))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKor_2)
                                            .addComponent(lblNev_2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNev_2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnFeldolgoz_2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnVeletlenszamok)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKor_1)
                            .addComponent(txtKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNev_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNev_1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKor_2)
                            .addComponent(numKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNev_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNev_2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFeldolgoz_1)
                    .addComponent(btnFeldolgoz_2))
                .addGap(18, 18, 18)
                .addComponent(lblVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVeletlenszamok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFeldolgoz_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeldolgoz_1ActionPerformed
        /* Bekérés: */
        String beKor = txtKor.getText();
        String beNev = txtNev_1.getText();   

        /* hogy tudjunk vele számolni: */
        int kor = Integer.parseInt(beKor);
        
        /* Ellenőrzés: */
        boolean jo = kor > 6 && beNev.length() >= 3;
        NevKor(jo, beNev, kor);
    }//GEN-LAST:event_btnFeldolgoz_1ActionPerformed

    private void btnFeldolgoz_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeldolgoz_2ActionPerformed
        Object beKor = numKor.getValue();
        String beNev = txtNev_2.getText();   
        
        /* hogy tudjunk vele számolni: */
        int kor = (int)beKor;
        
        /* Ellenőrzés: */
        boolean jo = beNev.length() >= 3;
        NevKor(jo, beNev, kor);
    }//GEN-LAST:event_btnFeldolgoz_2ActionPerformed

    private void NevKor(boolean jo, String beNev, int kor) throws HeadlessException {
        if(!jo){
            lblVisszajelzes.setText("Hibás adatok!");
        }else{
            String vissza = "neved: " + beNev +", korod: " + kor;
            lblVisszajelzes.setText(vissza);
            
            kor = kor + 1;
            JOptionPane.showMessageDialog(rootPane, "Szülinapod után a korod: " + kor);
        }
    }

    private void btnVeletlenszamokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeletlenszamokActionPerformed
        
        Koszones();

    }//GEN-LAST:event_btnVeletlenszamokActionPerformed

    private void Koszones() {
        //        int veletlenszam;
//        for (int i = 0; i < 10; i++) {
//            veletlenszam =+(int)(Math.random() * 21);
//            System.out.println(veletlenszam);
//            lblVisszajelzes.setText(veletlenszam+" ");
//        }
int db =(int)numKor.getValue();
int i= 0;
String s ="";
while (i <db-1) {
    int veletlenszam =+(int)(Math.random() * 21);
    s+= veletlenszam+", ";
    i++;
    
}
int veletlenszam =+(int)(Math.random() * 21);
s+= veletlenszam+" ";
lblVisszajelzes.setText(s);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFeldolgoz_1;
    private javax.swing.JButton btnFeldolgoz_2;
    private javax.swing.JButton btnVeletlenszamok;
    private javax.swing.JLabel lblKor_1;
    private javax.swing.JLabel lblKor_2;
    private javax.swing.JLabel lblNev_1;
    private javax.swing.JLabel lblNev_2;
    private javax.swing.JLabel lblVisszajelzes;
    private javax.swing.JSpinner numKor;
    private javax.swing.JTextField txtKor;
    private javax.swing.JTextField txtNev_1;
    private javax.swing.JTextField txtNev_2;
    // End of variables declaration//GEN-END:variables
}
